apiVersion: v1
kind: Pod
metadata:
  name: podtest1
  labels:
    app: frontend
    env: dev
spec:
  containers:
  - name: front
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: backend
    image: nginx:alpine
